apiVersion: v1
kind: Service
metadata:
  name: ome-node-service
spec:
  type: NodePort
  selector:
    app: tracer-ome
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
    nodePort: 32000